#!/bin/bash
yum install -y nagios-nrpe-server nagios-plugins nrpe nagios-plugins-load nagios-plugins-ping nagios-plugins-disk nagios-plugins-http nagios-plugins-procs wget
# BUG:https://osric.com/chris/accidental-developer/2016/12/missing-nagios-plugins-in-centos-7/ (nrpe plugins have been packaged seperately and don't install with nagios-plugins-all)
# BUG #2 https://cloudwafer.com/blog/installing-nagios-agent-npre-on-centos/ (the nrpe config is commented out and checks are not defined)
# Use sed statments to uncomment NRPE config and add the appropiate flags
# add in command[check_mem]=/usr/lib64/nagios/plugins/check_mem.sh
# Install custom mem monitor
wget -O /usr/lib64/nagios/plugins/check_mem.sh https://raw.githubusercontent.com/nic-instruction/NTI-320/master/nagios/check_mem.sh
systemctl enable nrpe
systemctl start nrpe

#make sure to change the ip to the server ipaddress.
sed -i 's/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1, 10.142.15.211/g' /etc/nagios/nrpe.cfg
sed -i "s,command[check_hda1]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /dev/hda1,command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /dev/sda1,g" /etc/nagios/nrpe.cfg

#restart the nrpe
systemctl restart nrpe

#Insert and change the command line. 
sed -i 's,#command\[check_users\]=/usr/lib64/nagios/plugins/check_users\$ARG\$,commannd\[check_users\]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10,g' nrpe.cfg

sed -i 's,#command\[check_load\]=/usr/lib64/nagios/plugins/check_load\$ARG\$,commannd\[check_load\]=/usr/lib64/nagios/plugins/check_load -w 15,10,5 -c 30,25,20,g' nrpe.cfg

sed -i 's,#command\[check_disk\]=/usr/lib64/nagios/plugins/check_disk\$ARG\$,commannd\[check_disk\]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10%,g' nrpe.cfg

sed -i 's,#command\[check_swap\]=/usr/lib64/nagios/plugins/check_swap\$ARG\$,commannd\[check_swap\]=/usr/lib64/nagios/plugins/check_swap -w 20% -c 10%,g' nrpe.cfg

sed -i 's,#command\[check_cpu_stats\]=/usr/lib64/nagios/plugins/check_cpu_stats.sh\$ARG\$,commannd\[check_cpu_stats\]=/usr/lib64/nagios/plugins/check_cpu_stats.sh -w 70,40,30, -c 90,50,40,g' nrpe.cfg

sed -i 's,#command\[check_mem\]=/usr/lib64/nagios/plugins/check_mem.sh\$ARG\$,commannd\[check_mem\]=/usr/lib64/nagios/plugins/check_mem.sh -w 80 -c 90,g' nrpe.cfg

#what it should look like.
#command[check_users]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10
#command[check_load]=/usr/lib64/nagios/plugins/check_load -w 15,10,5 -c 30,25,20
#command[check_disk]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10%
#command[check_swap]=/usr/lib64/nagios/plugins/check_swap -w 20% -c 10%
#command[check_cpu_stats]=/usr/lib64/nagios/plugins/check_cpu_stats.sh -w 70,40,30, -c 90,50,40
#command[check_mem]=/usr/lib64/nagios/plugins/check_mem.sh -w 80 -c 90

#command[check_users]=/usr/lib64/nagios/plugins/check_users -w 5 -c 10
#command[check_load]=/usr/lib64/nagios/plugins/check_load -r -w .15,.10,.05 -c .30,.25,.20
#command[check_hda1]=/usr/lib64/nagios/plugins/check_disk -w 20% -c 10% -p /dev/hda1
#command[check_zombie_procs]=/usr/lib64/nagios/plugins/check_procs -w 5 -c 10 -s Z
#command[check_total_procs]=/usr/lib64/nagios/plugins/check_procs -w 150 -c 200
